#!/usr/bin/env python3
"""Generate the shared Markdown robustness corpus for both platforms' tests.

Source: the official CommonMark spec examples (every `markdown` input), plus a
handful of pathological deeply-nested inputs that regression-test the parser's
recursion/nesting guards. The parsers implement a GFM *subset*, so we do NOT
compare output against the spec's expected HTML — the corpus is a stability
suite: every input must parse/render without crashing, hanging, or exhausting
the stack.

Inputs are embedded as base64 so the generated C++/Swift compile cleanly
regardless of quotes, backslashes, control bytes, or Unicode in the samples.

Usage:
    curl -s https://spec.commonmark.org/0.31.2/spec.json -o spec.json
    scripts/gen-spec-corpus.py spec.json
"""
import base64
import json
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def pathological(list_depth=3000, heading_len=100000):
    # Deep nesting that would blow an unguarded recursive parser/renderer
    # (both parsers guard at depth 100). The C++ header uses smaller variants
    # of the two biggest inputs: MSVC caps one string literal at 65535 bytes
    # (C1091), which the default indented list (quadratic size, ~12MB of
    # base64) and 100k-char heading blow past. 200 levels / 40000 chars still
    # exercise the same guards.
    return [
        "> " * 5000 + "x",
        "\n".join("  " * i + "- x" for i in range(list_depth)),
        "*" * 5000 + "x" + "*" * 5000,
        "~" * 5000 + "x" + "~" * 5000,
        "[" * 5000 + "x" + "](u)" * 5000,
        "`" * 20000,
        "#" * 6 + " " + "a" * heading_len,
    ]


def main():
    spec = json.loads(Path(sys.argv[1]).read_text())
    inputs = [ex["markdown"] for ex in spec]
    spec_count = len(inputs)

    def encode(extra):
        return [base64.b64encode(s.encode("utf-8")).decode("ascii")
                for s in inputs + extra]

    b64 = encode(pathological())
    b64_cpp = encode(pathological(list_depth=200, heading_len=40000))

    header = (
        f"CommonMark spec examples ({spec_count}, from spec.commonmark.org) + "
        f"{len(b64) - spec_count} pathological inputs. "
        "Generated by scripts/gen-spec-corpus.py — do not edit by hand."
    )

    # ---- Windows: C++ header ----
    # MSVC caps a single string-literal piece at 16380 chars (C2026); longer
    # inputs are emitted as adjacent literals the compiler concatenates.
    chunk = 16000
    cpp_items = "\n".join(
        "    " + " ".join(f'"{s[i:i + chunk]}"' for i in range(0, max(len(s), 1), chunk)) + ","
        for s in b64_cpp
    )
    (REPO / "windows/tests/spec_corpus.h").write_text(
        "#pragma once\n"
        f"// {header}\n\n"
        "namespace spec {\n"
        "inline const char* const kCorpusBase64[] = {\n"
        f"{cpp_items}\n"
        "};\n"
        f"inline constexpr int kCorpusCount = {len(b64)};\n"
        "} // namespace spec\n"
    )

    # ---- macOS: Swift array ----
    swift_items = "\n".join(f'    "{s}",' for s in b64)
    (REPO / "macos/Tests/SpecCorpus.swift").write_text(
        f"// {header}\n\n"
        "/// Base64-encoded Markdown inputs; decode with Data(base64Encoded:).\n"
        "let specCorpusBase64: [String] = [\n"
        f"{swift_items}\n"
        "]\n"
    )

    print(f"wrote {len(b64)} inputs "
          f"({spec_count} spec + {len(b64) - spec_count} pathological)")


if __name__ == "__main__":
    main()
